// regularExpression/jsRegexReference.js
// Created by Leonard Pauli, 25 jun 2018, based on contents by Mozilla Contributors
//
// This file is based on content by Mozilla Contributors
//   and this file is thereby licenced under CC-BY-SA 2.5.
//   see "Regular Expressions": https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions
//   see "CC-BY-SA 2.5": https://creativecommons.org/licenses/by-sa/2.5/


export default {
	default: [
		{ regex: /^\^/,
			char: '^',
			desc: 'Matches beginning of input.',
			info: 'If the multiline flag is set to true, also matches immediately after a line break character.',
			example: '/^A/ does not match the \'A\' in "an A", but does match the \'A\' in "An E".' },
		{ regex: /^\$/,
			char: '$',
			desc: 'Matches end of input.',
			info: 'If the multiline flag is set to true, also matches immediately before a line break character.',
			example: '/t$/ does not match the \'t\' in "eater", but does match it in "eat".' },
		{ regex: /^\*/,
			char: '*',
			desc: 'Matches the preceding expression 0 or more times. Equivalent to {0,}.',
			example: '/bo*/ matches \'boooo\' in "A ghost booooed" and \'b\' in "A bird warbled" but nothing in "A goat grunted".' },
		{ regex: /^\+/,
			char: '+',
			desc: 'Matches the preceding expression 1 or more times. Equivalent to {1,}.',
			example: '/a+/ matches the \'a\' in "candy" and all the a\'s in "caaaaaaandy", but nothing in "cndy".' },
		{ regex: /^\?/,
			char: '?',
			desc: 'Matches the preceding expression 0 or 1 time. Equivalent to {0,1}.',
			example: '/e?le?/ matches the \'el\' in "angel" and the \'le\' in "angle" and also the \'l\' in "oslo".',
			note: [
				'If used immediately after any of the quantifiers *, +, ?, or {}, makes the quantifier non-greedy (matching the fewest possible characters), as opposed to the default, which is greedy (matching as many characters as possible). applying /\\d+/ to "123abc" matches "123". But applying /\\d+?/ to that same string matches only the "1".',
				'Also used in lookahead assertions, as described in the x(?=y) and x(?!y) entries of this table.',
			] },
		{ regex: /^\{/,
			char: '{',
			retain: -1,
			open: 'matchCount',
			desc: 'Starts describing how many times the preceding token can match' },
		{ regex: /^\./,
			char: '.',
			note: '(The decimal point) matches any single character except the newline character.',
			example: '/.n/ matches \'an\' and \'on\' in "nay, an apple is on the tree", but not \'nay\'.' },
		{ regex: /^\[\^/,
			char: '[^',
			open: 'characterSet',
			desc: 'Starts a negative character set, anything not inside will match' },
		{ regex: /^\[/,
			char: '[',
			open: 'characterSet',
			desc: 'Starts a character set, only chars whitelisted inside will match' },
		{ regex: /^\\/,
			char: '\\',
			open: 'escapeOrSpecial',
			desc: 'A backslash indicates that the following character should be interpreted differently than by default (special, like \'.\' (matches ~any char), becomes normal (matches a dot), and normal, like d (matches a d), becomes special (matches a digit))',
			note: 'Do not forget to escape \\ itself while using the RegExp("pattern") notation because \\ is also an escape character in strings.' },
		{ regex: /^\(/, char: '(', open: 'group', desc: 'begins a group' },
		{ regex: /^\|/,
			char: '|',
			desc: 'Matches either side of it (or); x|y matches \'x\', or \'y\' (if there is no match for \'x\').',
			example: '/green|red/ matches \'green\' in "green apple" and \'red\' in "red apple." The order of \'x\' and \'y\' matters. For example a*|b matches the empty string in "b", but b|a* matches "b" in the same string.' },
	],
	characterSet: [
		{ regex: /^\]/, char: ']', close: true },
		{ regex: /^[xyz]/,
			char: '[xyz]',
			desc: 'Character set. This pattern type matches any one of the characters in the brackets, including escape sequences. Special characters like the dot(.) and asterisk (*) are not special inside a character set, so they don\'t need to be escaped. You can specify a range of characters by using a hyphen, as the following examples illustrate.',
			i: 'The pattern [a-d], which performs the same match as [abcd], matches the \'b\' in "brisket" and the \'c\' in "city". The patterns /[a-z.]+/ and /[\\w.]+/ match the entire string "test.i.ng".' },
		{ regex: /^[^xyz]/,
			char: '[^xyz]',
			desc: 'A negated or complemented character set. That is, it matches anything that is not enclosed in the brackets. You can specify a range of characters by using a hyphen. Everything that works in the normal character set also works here.',
			example: '[^abc] is the same as [^a-c]. They initially match \'r\' in "brisket" and \'h\' in "chop."' },
		{ regex: /^[\\b]/,
			char: '[\\b]',
			desc: 'Matches a backspace (U+0008). You need to use square brackets if you want to match a literal backspace character. (Not to be confused with \\b.)' },
	],
	matchCount: [
		{ regex: /^\}/, char: '}', close: true },
		{ regex: /^\{\d+\}/,
			char: '{n}',
			retain: -1,
			desc: 'Matches exactly n occurrences of the preceding expression. N must be a positive integer.',
			example: '/a{2}/ doesn\'t match the \'a\' in "candy," but it does match all of the a\'s in "caandy," and the first two a\'s in "caaandy."' },
		{ regex: /^\{\d+,\}/,
			char: '{n,}',
			retain: -1,
			desc: 'Matches at least n occurrences of the preceding expression. N must be a positive integer.',
			example: '/a{2,}/ will match "aa", "aaaa" and "aaaaa" but not "a"' },
		{ regex: /^\{\d+,\d+\}/,
			char: '{n,m}',
			retain: -1,
			desc: 'Where n and m are positive integers and n <= m. Matches at least n and at most m occurrences of the preceding expression. When m is omitted, it\'s treated as ∞.',
			example: '/a{1,3}/ matches nothing in "cndy", the \'a\' in "candy," the first two a\'s in "caandy," and the first three a\'s in "caaaaaaandy". Notice that when matching "caaaaaaandy", the match is "aaa", even though the original string had more a\'s in it.' },
	],
	group: [
		{ regex: /^\)/, char: ')', close: true, desc: 'closes group' },
		{ regex: /^(x)/,
			char: '(x)',
			desc: 'Matches \'x\' and remembers the match, as the following example shows. The parentheses are called capturing parentheses.',
			note: 'The \'(foo)\' and \'(bar)\' in the pattern /(foo) (bar) \\1 \\2/ match and remember the first two words in the string "foo bar foo bar". The \\1 and \\2 in the pattern match the string\'s last two words. Note that \\1, \\2, ..., \n are used in the matching part of the regex. In the replacement part of a regex the syntax $1, $2, ..., $n must be used, e.g.: \'bar foo\'.replace(/(...) (...)/, \'$2 $1\').  $& means the whole matched string.' },
		{ regex: /^(?:x)/,
			char: '(?:x)',
			desc: 'Matches \'x\' but does not remember the match. The parentheses are called non-capturing parentheses, and let you define subexpressions for regular expression operators to work with. Consider the sample expression /(?:foo){1,2}/. If the expression was /foo{1,2}/, the {1,2} characters would apply only to the last \'o\' in \'foo\'. With the non-capturing parentheses, the {1,2} applies to the entire word \'foo\'. For more information, see Using parentheses below.' },
		{ regex: /^x(?=y)/,
			char: 'x(?=y)',
			desc: 'Matches \'x\' only if \'x\' is followed by \'y\'. This is called a lookahead.',
			example: '/Jack(?=Sprat)/ matches \'Jack\' only if it is followed by \'Sprat\'. /Jack(?=Sprat|Frost)/ matches \'Jack\' only if it is followed by \'Sprat\' or \'Frost\'. However, neither \'Sprat\' nor \'Frost\' is part of the match results.' },
		{ regex: /^x(?!y)/,
			char: 'x(?!y)',
			desc: 'Matches \'x\' only if \'x\' is not followed by \'y\'. This is called a negated lookahead.',
			example: '/\\d+(?!\\.)/ matches a number only if it is not followed by a decimal point. The regular expression /\\d+(?!\\.)/.exec("3.141") matches \'141\' but not \'3.141\'.' },
	],
	escapeOrSpecial: [
		{ regex: /^\\/,
			char: '\\',
			desc: 'Matches a backslash',
			example: '\\\\' },
		{ regex: /^\//,
			char: '/',
			desc: 'Matches a (forward-) slash',
			example: '\\/' },
		{ regex: /^\(/,
			char: '(',
			desc: 'Matches an opening parentheses',
			example: '\\(' },
		{ regex: /^\)/,
			char: ')',
			desc: 'Matches a closing parentheses',
			example: '\\)' },
		{ regex: /^\[/,
			char: '[',
			desc: 'Matches an opening bracket',
			example: '\\[' },
		{ regex: /^\]/,
			char: ']',
			desc: 'Matches a closing bracket',
			example: '\\]' },
		{ regex: /^b/,
			char: 'b',
			desc: 'Matches a word boundary. A word boundary matches the position where a word character is not followed or preceded by another word-character. Note that a matched word boundary is not included in the match. In other words, the length of a matched word boundary is zero. (Not to be confused with [\\b].)',
			example: [
				'/\\bm/ matches the \'m\' in "moon" ;',
				'/oo\\b/ does not match the \'oo\' in "moon", because \'oo\' is followed by \'n\' which is a word character;',
				'/oon\\b/ matches the \'oon\' in "moon", because \'oon\' is the end of the string, thus not followed by a word character;',
				'/\\w\\b\\w/ will never match anything, because a word character can never be followed by both a non-word and a word character.',
			],
			note: 'JavaScript\'s regular expression engine defines a specific set of characters to be "word" characters. Any character not in that set is considered a word break. This set of characters is fairly limitedesc: it consists solely of the Roman alphabet in both upper- and lower-case, decimal digits, and the underscore character. Accented characters, such as "é" or "ü" are, unfortunately, treated as word breaks.' },
		{ regex: /^B/,
			char: 'B',
			desc: 'Matches a non-word boundary.',
			info: [
				'Before the first character of the string, if the first character is not a word character.',
				'After the last character of the string, if the last character is not a word character.',
				'Between two word characters',
				'Between two non-word characters',
				'The empty string',
				'The beginning and end of a string are considered non-words.',
			],
			example: '/\\B../ matches \'oo\' in "noonday", and /y\\B./ matches \'ye\' in "possibly yesterday."' },
		{ regex: /^c[A-Z]/,
			char: 'cX',
			desc: 'Where X is a character ranging from A to Z. Matches a control character in a string.',
			example: '/\\cM/ matches control-M (U+000D) in a string.' },
		{ regex: /^d/,
			char: 'd',
			desc: 'Matches a digit character. Equivalent to [0-9].',
			example: '/\\d/ or /[0-9]/ matches \'2\' in "B2 is the suite number."' },
		{ regex: /^D/,
			char: 'D',
			desc: 'Matches a non-digit character. Equivalent to [^0-9].',
			example: '/\\D/ or /[^0-9]/ matches \'B\' in "B2 is the suite number."' },
		{ regex: /^f/, char: 'f', desc: 'Matches a form feed (U+000C).' },
		{ regex: /^n/, char: 'n', desc: 'Matches a line feed (U+000A).' },
		{ regex: /^r/,
			char: 'r',
			desc: 'Matches a carriage return (U+000D).' },
		{ regex: /^s/,
			char: 's',
			desc: 'Matches a single white space character, including space, tab, form feed, line feed. Equivalent to [ \\f\\n\\r\\t\\v\\u00a0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000\\ufeff].',
			example: '/\\s\\w*/ matches \' bar\' in "foo bar."' },
		{ regex: /^S/,
			char: 'S',
			desc: 'Matches a single character other than white space. Equivalent to [^ \\f\\n\\r\\t\\v\\u00a0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000\\ufeff].',
			example: '/\\S*/ matches \'foo\' in "foo bar."' },
		{ regex: /^t/, char: 't', desc: 'Matches a tab (U+0009).' },
		{ regex: /^v/,
			char: 'v',
			desc: 'Matches a vertical tab (U+000B).' },
		{ regex: /^w/,
			char: 'w',
			desc: 'Matches any alphanumeric character including the underscore. Equivalent to [A-Za-z0-9_].',
			example: '/\\w/ matches \'a\' in "apple," \'5\' in "$5.28," and \'3\' in "3D."' },
		{ regex: /^W/,
			char: 'W',
			desc: 'Matches any non-word character. Equivalent to [^A-Za-z0-9_].',
			example: '/\\W/ or /[^A-Za-z0-9_]/ matches \'%\' in "50%."' },
		{ regex: /^\d+/,
			char: 'n',
			desc: 'Where n is a positive integer, a back reference to the last substring matching the n parenthetical in the regular expression (counting left parentheses).',
			example: '/apple(,)\\sorange\\1/ matches \'apple, orange,\' in "apple, orange, cherry, peach."' },
		{ regex: /^0/,
			char: '0',
			desc: 'Matches a NULL (U+0000) character. Do not follow this with another digit, because \\0<digits> is an octal escape sequence. Instead use \\x00.' },
		{ regex: /^x[A-f0-9]{2}/,
			char: 'xhh',
			desc: 'Matches the character with the code hh (two hexadecimal digits)' },
		{ regex: /^u[A-f0-9]{4}/,
			char: 'uhhhh',
			desc: 'Matches the character with the code hhhh (four hexadecimal digits).' },
		{ regex: /^u\{[A-f0-9]{4}\}/,
			char: 'u{hhhh}',
			desc: '(only when u flag is set) Matches the character with the Unicode value hhhh (hexadecimal digits).' },
	],
	flags: [
		{ regex: /^g/, char: 'g', desc: 'Global search.' },
		{ regex: /^i/, char: 'i', desc: 'Case-insensitive search.' },
		{ regex: /^m/, char: 'm', desc: 'Multi-line search.' },
		{ regex: /^u/,
			char: 'u',
			desc: 'unicode; treat a pattern as a sequence of unicode code points' },
		{ regex: /^y/,
			char: 'y',
			desc: 'Perform a "sticky" search that matches starting at the current position in the target string. See sticky' },
	],
}
